### PR TITLE
Fixing issues with searchbox on cellphone and small screens + bootstrap upgrade

### PR DESCRIPTION
**Pull request by eklem**
Moved the searchbox out of the header, made it wider big screens, and smaller (by steps) on small screens, but utilising the with of the screen.

Changes only done to the css/norch-bootstrap.css-file and the index.js-file.

 Also upgraded bootstrap from v.3.3.1 to v3.3.4.

### CODE REVIEW

**Comment by eklem** [comment]
The error with the too wide search box was a hardcoded width in norch-bootstrap.css. And I moved the search box out of the header to make it visible all the time, on all devices.

**Comment by mewwts** [comment]
Cool! I'm assigning myself to this!

**Comment by mewwts** [comment]
It seems like I was too slow @eklem @fergiemcdowall  :-1:

**Comment by eklem** [comment]
Nice to hear that my pull request was popular =)

**Pull request merged**
